@startuml
package com.directi.training.lsp.exercise {
    class Duck {
        +quack()
        +swim()
    }
    class ElectronicDuck {
        -_on : boolean
        +quack()
        +swim()
        +turnOn()
        +turnOff()
    }
    Duck <|-- ElectronicDuck

    class Pool {
        +run()
        -quack(duck: Duck[])
        -swim(duck: Duck[])
        +main(String[] args)
    }
}
@enduml
