@startuml
package com.directi.training.lsp.exercise {
    interface IDuck {
        +quack()
        +swim()
    }
    
    class NaturalDuck {
        +quack()
        +swim()
    }
    NaturalDuck ..|> IDuck

    class ElectronicDuck {
        -_on : boolean
        +quack()
        +swim()
        +turnOn()
        +turnOff()
    }
    
    class ElectronicDuckAdapter {
        -electronicDuck : ElectronicDuck
        +quack()
        +swim()
    }
    ElectronicDuckAdapter ..|> IDuck

    class Pool {
        +run()
        -quack(ducks: IDuck[])
        -swim(ducks: IDuck[])
        +main(String[] args)
    }
}
@enduml
