@startuml
interface Door {
    void lock()
    void unlock()
    void open()
    void close()
}

interface TimerClient {
    void timeOutCallback()
}

interface ProximitySensorClient {
    void proximityCallback()
}

class SensingDoor {
    +SensingDoor(Sensor)
}

class TimedDoor {
    +TimedDoor(Timer)
}

class Sensor {
    +register(ProximitySensorClient)
}

class Timer {
    +register(long, TimerClient)
}

SensingDoor .up.|> Door
SensingDoor .up.|> ProximitySensorClient
TimedDoor .up.|> Door
TimedDoor .up.|> TimerClient
Sensor --> ProximitySensorClient
Timer --> TimerClient
@enduml