@startuml
interface Door {
    void lock()
    void unlock()
    void open()
    void close()
    void timeOutCallback()
    void proximityCallback()
}

class SensingDoor {
    +SensingDoor(Sensor)
}

class TimedDoor {
    +TimedDoor(Timer)
}

class Sensor {
    +register(Door)
}

class Timer {
    +register(long, Door)
}

SensingDoor .up.|> Door
TimedDoor .up.|> Door
Sensor --> Door
Timer --> Door
@enduml