@startuml
package com.directi.training.dip.exercise {
  class EncodingModule {
    +encodeWithFiles()
    +encodeBasedOnNetworkAndDatabase()
  }
  class EncodingModuleClient {
    +main()
  }
  class MyDatabase {
    +write()
  }
  EncodingModule --> FileReader
  EncodingModule --> FileWriter
  EncodingModule --> URL
  EncodingModule --> InputStream
  EncodingModule --> MyDatabase
  EncodingModuleClient --> EncodingModule
}
@enduml