@startuml
package com.directi.training.dip.exercise_refactored {
  interface IReader {
    +read() : List<String>
  }
  interface IWriter {
    +write(List<String>)
  }
  class EncodingModule {
    +encode(IReader, IWriter)
  }
  class FileReader implements IReader 
  class NetworkReader implements IReader 
  class FileWriter implements IWriter 
  class DatabaseWriter implements IWriter 
  class MyDatabase {
    +write()
  }
  
  EncodingModule --> IReader
  EncodingModule --> IWriter
  DatabaseWriter --> MyDatabase
  EncodingModuleClient --> EncodingModule
  EncodingModuleClient --> FileReader
  EncodingModuleClient --> FileWriter
  EncodingModuleClient --> NetworkReader
  EncodingModuleClient --> MyDatabase
  EncodingModuleClient --> DatabaseWriter
}
@enduml