@startuml
package com.directi.training.ocp.exercise {
  class ResourceAllocator {
    - INVALID_RESOURCE_ID: int
    + allocate(ResourceType): int
    + free(ResourceType, int)
    - markSpaceSlotFree(int)
    - markTimeSlotFree(int)
    - markSpaceSlotBusy(int)
    - findFreeSpaceSlot(): int
    - markTimeSlotBusy(int)
    - findFreeTimeSlot(): int
  }

  enum ResourceType {
    TIME_SLOT
    SPACE_SLOT
  }
}
@enduml