@startuml
package com.directi.training.ocp.exercise_refactored {
  interface ResourceHandler {
    + allocate(): int
    + free(int)
  }

  class TimeSlotHandler {
    + allocate(): int
    + free(int)
    - findFreeTimeSlot(): int
    - markTimeSlotBusy(int)
    - markTimeSlotFree(int)
  }

  class SpaceSlotHandler {
    + allocate(): int
    + free(int)
    - findFreeSpaceSlot(): int
    - markSpaceSlotBusy(int)
    - markSpaceSlotFree(int)
  }

  class ResourceAllocator {
    - handlers: Map<ResourceType, ResourceHandler>
    + ResourceAllocator(Map<ResourceType, ResourceHandler>)
    + allocate(ResourceType): int
    + free(ResourceType, int)
  }

  enum ResourceType {
    TIME_SLOT
    SPACE_SLOT
  }

  ResourceAllocator --> ResourceType
  ResourceAllocator --> ResourceHandler
  ResourceHandler <|.. TimeSlotHandler
  ResourceHandler <|.. SpaceSlotHandler
}
@enduml